src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: BookRepository::class)]
#[ORM\Table("web_book")]
#[ORM\HasLifecycleCallbacks]

#[UniqueEntity(
    fields: ['isbn_no'],
    errorPath: 'isbn_no',
    message: 'This port is already in use on that host.',
)]

class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $isbn_no = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $price = null;

    #[ORM\Column(length: 255)]
    private ?string $page_no = null;

    #[ORM\Column(length: 255)]
    private ?string $edition = null;

    #[ORM\Column(length: 255)]
    private ?string $publisher = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column(length: 255)]
    private ?string $language = null;

    #[ORM\Column(length: 255)]
    private ?string $binding = null;

    #[ORM\Column]
    private ?array $genre = [];

    #[ORM\Column(length: 255)]
    private ?string $available_book = null;

    #[ORM\Column(length: 255)]
    private ?string $file = null;
    
    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: "string", columnDefinition: "ENUM('Active', 'Deleted')")]
    private ?string $status=null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated = null;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: CartItem::class)]
    private Collection $cartItem;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: OrderItem::class)]
    private Collection $orderItems;


    public function __construct()
    {
        $this->status = 'Active';
        $this->cartItem = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbnNo(): ?string
    {
        return $this->isbn_no;
    }

    public function setIsbnNo(string $isbn_no): static
    {
        $this->isbn_no = $isbn_no;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getPageNo(): ?string
    {
        return $this->page_no;
    }

    public function setPageNo(string $page_no): static
    {
        $this->page_no = $page_no;

        return $this;
    }

    public function getEdition(): ?string
    {
        return $this->edition;
    }

    public function setEdition(string $edition): static
    {
        $this->edition = $edition;

        return $this;
    }

    public function getPublisher(): ?string
    {
        return $this->publisher;
    }

    public function setPublisher(string $publisher): static
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): static
    {
        $this->language = $language;

        return $this;
    }

    public function getBinding(): ?string
    {
        return $this->binding;
    }

    public function setBinding(string $binding): static
    {
        $this->binding = $binding;

        return $this;
    }

    public function getAvailableBook(): ?string
    {
        return $this->available_book;
    }

    public function setAvailableBook(string $available_book): static
    {
        $this->available_book = $available_book;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreated(): void
    {
        $this->created = new \DateTimeImmutable();
        $this->setUpdated();
    }

    #[ORM\PreUpdate]
    public function setUpdated(): void
    {
        $this->updated = new \DateTimeImmutable();
    }

    public function getGenre(): array
    {
        return $this->genre;
    }

    public function setGenre(array $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    /**
     * @return Collection<int, CartItem>
     */
    public function getCartItem(): Collection
    {
        return $this->cartItem;
    }

    public function addCartItem(CartItem $cartItem): static
    {
        if (!$this->cartItem->contains($cartItem)) {
            $this->cartItem->add($cartItem);
            $cartItem->setBook($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): static
    {
        if ($this->cartItem->removeElement($cartItem)) {
            // set the owning side to null (unless already changed)
            if ($cartItem->getBook() === $this) {
                $cartItem->setBook(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setBook($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getBook() === $this) {
                $orderItem->setBook(null);
            }
        }

        return $this;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Cart;
use App\Entity\CartItem;
use App\Entity\ShippingAddress;
use App\Entity\User;
use App\Form\ShippingAddressType;
use App\Form\UserType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class UserController extends AbstractController
{

    #[Route('/shopkeeper/dashboard', name: 'web_shopkeeper_dashboard')]
    public function shopkeeperDashboard(): Response
    {
        return $this->render('shopkeeper/shopkeeper_dashboard.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }
    #[Route('/feedback', name: 'feedback')]
    public function feedback(): Response
    {
        return $this->render('user/feedback.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }
    #[Route('/vendor/dashboard', name: 'web_vendor_dashboard')]
    public function vendorDashboard(): Response
    {
        return $this->render('user/vendor_dashboard.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }
    #[Route('/customer/dashboard', name: 'web_customer_dashboard')]
    public function customerDashboard(): Response
    {
        return $this->render('user/customer_dashboard.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    #[Route('/sign/up', name: 'web_sign_up')]
    public function manageUser(Request $request, ManagerRegistry $doctrine, UserPasswordHasherInterface $passwordHasher): Response
    {
        $em = $doctrine->getManager();
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        $msg = '0';
        $icon = '0';
        if ($request->getMethod() == "POST") {

            if ($form->isSubmitted() and $form->isValid()) {
                $user->setPassword($passwordHasher->hashPassword($user, $request->get("pass")));
                $em->persist($user);
                $em->flush();
                $msg = "you have registered successfully";
                $icon = "success";
            }
        }
        return $this->render('user/sign_up.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
            'msg' => $msg,
            'cv' => $icon
        ]);
    }

    #[Route('/user/verify/email/', name: 'verify_email')]
    public function verifyEmail(Request $request, ManagerRegistry $doctrine): Response
    {
        $error = 'false';
        if ($request->getMethod() == "POST") {

            $email = $request->get('email_id');
            $user = $doctrine->getRepository("App\Entity\User")->findOneBy(["email" => $email]);
            if ($user) {
                return $this->redirect($this->generateUrl('reset_password', ['id' => $user->getId()]));
            } else {
                $error = true;
            }
        }
        return $this->render('user/verify_email.html.twig', [
            'controller_name' => 'UserController',
            'error' => $error
        ]);
    }
    #[Route('/user/reset/password/{id}', name: 'reset_password')]
    public function resetPassword(Request $request, UserPasswordHasherInterface $passwordHasher, ManagerRegistry $doctrine, $id = -1): Response
    {
        $em = $doctrine->getManager();
        $user = $doctrine->getRepository("App\Entity\User")->findOneBy(["id" => $id]);
        $error = 'false';
        $is_changed = 'no';

        if ($request->getMethod() == "POST") {
            if ($user->getId()) {
                $new = $request->get('new_password');
                $con = $request->get('con_password');
                if ($new == $con) {
                    $user->setPassword($passwordHasher->hashPassword($user, $request->get('con_password')));
                    $em->persist($user);
                    $em->flush();
                    $is_changed = 'yes';
                } else {
                    $error = 'true';
                }
            }
            // $email = $request->get('email_id');
            // if ($user) {
            //     return $this->redirect($this->generateUrl('reset_password', ['id' => $user->getId()]));
            // } else {
            //     $error=true;
            // }

        }
        return $this->render('user/reset_password.html.twig', [
            'controller_name' => 'UserController',
            'error' => $error,
            'is_changed' => $is_changed
        ]);
    }

    #[Route('/book/details/{id}/{item}', name: 'web_book_details')]
    public function bookDetails(Request $request, ManagerRegistry $doctrine, $id, $item = 'no'): Response
    {
        $cart = $doctrine->getRepository("App\Entity\Cart")->findOneBy(["user" => $this->getUser()]);
        $book = $doctrine->getRepository("App\Entity\Book")->findOneBy(["id" => $id]);
        $cart_item = $doctrine->getRepository("App\Entity\CartItem")->findOneBy(["cart" => $cart, 'book' => $book]);
        if (!$cart_item) {
            $cart_present = '0';
        } elseif ($cart_item->getStatus() != "Active") {
            $cart_present = '0';
        } else {
            $cart_present = '1';
            $item = 'yes';
        }
        return $this->render('user/book_details.html.twig', [
            'controller_name' => 'UserController',
            'book' => $book,
            'item_present' => $item,
            'cart_item' => $cart_present
        ]);
    }
    #[Route('/ajax/book/details', name: 'web_ajax_book_details')]
    public function ajaxView(ManagerRegistry $mr, Request $request): JsonResponse
    {
        $book = $mr->getRepository("App\Entity\Book")->findOneBy(["id" => $request->get('id')]);
        $html = $this->renderView('user/ajaxView.html.twig', [
            'title' => "View User",
            'book' => $book,
        ]);
        $response = new JsonResponse();
        $response->setData($html);
        return $response;
    }

    #[Route('/book/cart/{id}', name: 'add_cart')]
    public function bookCart(Request $request, ManagerRegistry $doctrine, $id): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $em = $doctrine->getManager();
        $cart = $doctrine->getRepository("App\Entity\Cart")->findOneBy(["user" => $this->getUser()]);
        $book = $doctrine->getRepository("App\Entity\Book")->findOneBy(["id" => $id]);
        $cart_item = $doctrine->getRepository("App\Entity\CartItem")->findOneBy(["cart" => $cart, 'book' => $book]);

        if (!$cart_item) {
            $cart_item = new CartItem();
            $cart_item->setCart($cart);
            $cart_item->setBook($book);
            $cart_item->setQuantity('1');
            $em->persist($cart_item);
            // dd($cart_item);
            $em->flush();
            $item_present = 'yes';
        } elseif ($cart_item->getStatus() != "Active") {
            $cart_item->setStatus('Active');
            $cart_item->setQuantity('1');
            $em->persist($cart_item);
            $em->flush();
            $item_present = 'yes';
        } else {
            $item_present = 'yes';
        }


        return $this->redirect($this->generateUrl('web_book_details', ['id' => $id, 'item' => $item_present]));
    }

    #[Route('/view/cart/items/{shipping}', name: 'view_cart')]
    public function viewCart(Request $request, ManagerRegistry $doctrine, $shipping = -1): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($shipping > 0) {
            $address = $shipping;
        } else {
            $address = '-1';
        }
        $count = 0;
        foreach ($this->getUser()->getCart()->getCartItem() as $item) {

            if ($item->getStatus() == 'Active') {
                $count = $count + 1;
            }
        }
        if ($count == 0) {
            $cart_present = "no";
        } else {
            $cart_present = "yes";
        }

        return $this->render('user/view_cart_items.html.twig', [
            'existCart' => $cart_present,
            'address' => $address
        ]);
    }
    #[Route('/remove/item/{id}/{shipping}', name: 'remove_cart_item')]
    public function RemoveItem(ManagerRegistry $doctrine, $id, $shipping = -1): Response
    {
        if ($shipping > 0) {
            $address = $shipping;
        } else {
            $address = '-1';
        }
        $em = $doctrine->getManager();
        $cart = $doctrine->getRepository("App\Entity\Cart")->findOneBy(['user' => $this->getUser()]);
        $book = $doctrine->getRepository("App\Entity\Book")->findOneBy(['id' => $id]);
        $a = $book->getId();
        $cart_item = $doctrine->getRepository("App\Entity\CartItem")->findOneBy(['cart' => $cart, 'book' => $a]);
        $cart_item->setStatus("Deleted");
        $em->persist($cart_item);
        $em->flush();
        return $this->redirect($this->generateUrl('view_cart', ['shipping' => $address]));
    }

    #[Route('/ajax/quantity', name: 'web_ajax_book_quantity')]
    public function updateQuantity(Request $request, ManagerRegistry $doctrine): JsonResponse
    {
        $em = $doctrine->getManager();
        $cart = $doctrine->getRepository("App\Entity\Cart")->findOneBy(['user' => $this->getUser()]);
        $book = $doctrine->getRepository("App\Entity\Book")->findOneBy(['id' => $request->get('book_id')]);
        $bk = $request->get('book_id');
        $price = $book->getPrice();
        $a = $book->getId();

templates/user/ajaxView.html.twig
{% extends 'base.html.twig' %}
{% block bootstrap %}
{{parent()}}
{% endblock %}
{% block body %}

<div class="row py-7">
    <div class="col-7">
        <div class="py-4 px-5 m-5 bg-light">
            <h1 class="bg-light py-2 m-3 text-center text-black">Book Details</h1>
            <div class="container back">
                <div class="table-wrapper">
                    <div class="table-title">
                        <div class="row"></div>
                    </div>
                    <table class="table table-striped table-hover color py-5" cellpadding="0" cellspacing="0" border="0"
                        class="display table table-bordered" id="hidden-table-info">
                        <tbody>

                            <tr>
                                <th>Title</th>
                                <td>{{book.title}}</td>
                              
                            </tr>
                            <tr>
                                <th>publisher</th>
                                <td>{{book.publisher}}</td>
                              
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td>{{book.description}}</td>
                              
                            </tr>

                            <tr>
                                
                                <th>Author</th>
                                <td>{{book.author}}</td>
                            </tr>
                            <tr>
                                <th>Language</th>
                                <td>{{book.language}}</td>
                            </tr>

                            <tr>
                               
                                <th>Binding</th>
                                <td>{{book.binding}}</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/book_details.html.twig
{% extends 'base.html.twig' %}
{% block bootstrap %}
{{parent()}}
{% endblock %}
{% block stylesheets %}
{{(parent())}}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
	.checked {
		color: yellow;
		font-size: 20px;
	}

	.unchecked {
		font-size: 20px;
	}

	th {
		font-size: 15px;
	}

	td {
		font-size: 15px;
	}

	.tab {
		overflow: hidden;
		border: 1px solid #ccc;
		background-color: #f1f1f1;
	}

	/* Style the buttons inside the tab */
	.tab button {
		background-color: inherit;
		float: left;
		border: none;
		outline: none;
		cursor: pointer;
		padding: 14px 16px;
		transition: 0.3s;
		font-size: 17px;
	}

	/* Change background color of buttons on hover */
	.tab button:hover {
		background-color: #ddd;
	}

	/* Create an active/current tablink class */
	.tab button.active {
		background-color: cadetblue
	}

	/* Style the tab content */
	.tabcontent {

		padding: 0px 12px;
		border: 1px solid #b39292;
		width: 100%;

	}
</style>
{% endblock %}
{% block body %}

<div class="row py-5" style="background-color: rgb(240, 251, 251);">
	<div class="col-md-5 py-3 col-sm-6">
		<div class="product-main-image py-5" style="position: relative; overflow: hidden;">
			<img src="{{path('image_show',{path:'books',file: book.file})}}"
				alt="Buy Harry Potter And The Chamber Of Secrets Book By J. K. Rowling | BookWorm"
				class=" img-responsive shadow-lg" style="border: 1px solid black; height:460px; width:550px;"
				itemprop="image">
			<img src="{{path('image_show',{path:'books',file: book.file})}}" class="zoomImg"
				style="position: absolute; top: -66.8299px; left: -33.7977px; opacity: 0; width: 300px; height: 461px; border: none; max-width: none;">
		</div>
		<p>
			<strong>Supplemental materials are not guaranteed for used textbooks or rentals
			</strong>
			(access codes, DVDs, CDs, workbooks).
		</p>

	</div>
	<div class="col-md-7 py-5">
		<div class=" mt-3 bg-white shadow-lg" style="width: 100%;">

			<div class="tab">
				<button class="tablinks active" id="cart">Do Cart</button>
				<button class="tablinks" id="description">Book Description</button>
				<button class="tablinks" id="specification">Book Specification</button>
			</div>

			<div id="book_cart" class="tabcontent">
				<div class="container m-3">
					<span style="font-size: 30px;">{{book.title}}</span>
					<span style="font-size: 15px;">
						({{book.binding}})</span>
					<br>
					<span>By:
						<span style="color: red;font-size: 15px;">{{book.author}}
						</span>(Author)</span>
					<br><br>
					<!-- <div class="row row-cols-1 row-cols-lg-4  g-5 py-5"></div> -->
					<span class="fa fa-star checked"></span>
					<span class="fa fa-star checked"></span>
					<span class="fa fa-star checked"></span>
					<span class="fa fa-star checked"></span>
					<span class="fa fa-star unchecked"></span>4/5

					<p class="pb-2 border-bottom"></p>
					<small>
						<s>MRP: ₹{{book.price+169}}</s>
					</small>
					<h3 class="py-2" style="color: blue;">
						<b>MRP: ₹{{book.price}}</b>
					</h3>
					<h5 style="color:gray;">(inclusive all taxes)</h5>

					{% if book.availableBook > 0 %}
					<p style="color: green; font-size: 15px;">Available</p>
					{% else %}
					<p style="color: red;font-size: 12px;">Stock Out</p>
					{% endif %}
					<p style="color: gray;font-size: 15px;">Seller: Bookworm</p>
					<p style="color: gray;font-size: 15px;">Dispatch time: 4-5 working days</p>

					<div class="text-center cart_div">
						{% if item_present == 'no' %}
						<p id="ab">
							<a href="{{path('add_cart',{id: book.id})}}"
								style="width: 290px; height: 65px;font-size: 20px;"
								class="btn btn-lg btn-danger bi bi-cart py-3 shadow-lg" id="add_cart"
								title="Add to cart" data-toggle="tooltip">Add to cart
							</a>
						</p>
						{% elseif cart_item == '1' %}
						<p id="ab">
							<a href="{{path('view_cart')}}" style="width: 290px; height: 65px;font-size: 20px;"
								class="btn btn-lg btn-danger bi bi-cart py-3 shadow-lg" id="add_cart" title="Go to cart"
								data-toggle="tooltip">Go To Cart
							</a>
						</p>
						{% else %}
						<p id="ab">
							<a href="{{path('add_cart',{id: book.id})}}"
								style="width: 290px; height: 65px;font-size: 20px;"
								class="btn btn-lg btn-danger bi bi-cart py-3 shadow-lg" id="add_cart"
								title="Add to cart" data-toggle="tooltip">Add to cart
							</a>
						</p>
						{% endif %}
					</div>
				</div>
			</div>

			<div id="book_description" class="tabcontent" style="display: none;">
				<div class="container mt-3 bg-white shadow-lg" style="height: 390px;">
					<p class="py-3 px-3" style="font-size: 16px;">{{book.description}}</p>
				</div>
			</div>

			<div id="book_specification" class="tabcontent" style="display:none;">
				<div class="py-1 shadow-lg bg-light">
					<!-- <h1 class="bg-light shadow-lg py-2 m-3 text-center text-black">Book Specification</h1> -->
					<p class="pb-3 border-bottom"></p>
					<div class="container">
						<div class="table-wrapper">
							<div class="table-title">
								<div class="row"></div>
							</div>
							<table class="bg-light shadow-lg table table-hover color py-3"
								style="border-spacing: 30px; height: 359px;" id="hidden-table-info">
								<tbody class="m-3">

									<tr>
										<th>Title</th>
										<td>{{book.title}}</td>
										<th>Availability</th>
										{% if book.availableBook > 0 %}
										<td>In stock</td>
										{% else %}
										<td>Stock out</td>
										{% endif %}

									</tr>

									<tr>
										<th>ISBN number</th>
										<td>{{book.isbnNo}}</td>

										<th>Binding</th>
										<td>{{book.binding}}</td>
									</tr>

									<tr>
										<th>Price</th>
										<td>{{book.price}}</td>

										<th>Edition</th>
										<td>{{book.edition}}</td>
									</tr>

									<tr>
										<th>Pages</th>
										<td>{{book.pageNo}}</td>

										<th>Author</th>
										<td>{{book.author}}</td>
									</tr>

									<tr>
										<th>publisher</th>
										<td>{{book.publisher}}</td>

										<th>Language</th>
										<td>{{book.language}}</td>
									</tr>

								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block javascripts %}
{{parent()}}
<script>
	$(document).ready(function () {
		$('#cart').click(function () {
			$('#book_description').hide();
			$('#book_specification').hide();
			$('#description').removeClass('active');
			$('#specification').removeClass('active');
			$('#cart').addClass('active');
			$('#book_cart').show();
		});

		$('#description').click(function () {

			$('#cart').removeClass('active');
			$('#specification').removeClass('active');
			$('#description').addClass('active');
			$('#book_cart').hide();
			$('#book_specification').hide();
			$('#book_description').show();

		});

		$('#specification').click(function () {

			$('#cart').removeClass('active');
			$('#description').removeClass('active');
			$('#specification').addClass('active');
			$('#book_cart').hide();
			$('#book_description').hide();
			$('#book_specification').show();

		});
	})
</script>
{% endblock %}

templates/user/feedback.html.twig
{% extends 'base.html.twig' %}
{% block bootstrap %}
	{{parent()}}
{% endblock %}
{% block body %}
	<section class="vh-100 gradient-custom">
		<div class="container py-5 h-100">
			<div class="row d-flex justify-content-center align-items-center h-100">
				<div class="col-12 col-md-8 col-lg-6 col-xl-5">
					<div class="card bg-dark text-white" style="border-radius: 1rem;">
						<div class="card-body p-5 text-center">

							<div class="mb-md-5 mt-md-4 pb-5">

								<h2 class="fw-bold mb-2">Feedback</h2>

								<div
									class="form-outline form-white mb-4">
									{# <input type="textarea" id="typePasswordX" class="form-control form-control-lg"/> #}

									<textarea id="typePasswordX" name="w3review" class="form-control form-control-lg" rows="4" cols="50"></textarea>
									<label class="form-label" for="typePasswordX">Enter your feedback</label>
								</div>

								<button class="btn btn-outline-light btn-lg px-5" type="submit">Submit</button>

								<div class="d-flex justify-content-center text-center mt-4 pt-1">
									<a href="#!" class="text-white">
										<i class="fab fa-facebook-f fa-lg"></i>
									</a>
									<a href="#!" class="text-white">
										<i class="fab fa-twitter fa-lg mx-4 px-2"></i>
									</a>
									<a href="#!" class="text-white">
										<i class="fab fa-google fa-lg"></i>
									</a>
								</div>

							</div>

							<div>
								<p class="mb-0">Don't have an account?
									<a href="#!" class="text-white-50 fw-bold">Sign Up</a>
								</p>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block javascripts %}
	{{parent()}}
{% endblock %}

templates/user/fetch_pin_code.html.twig
{{print}}

templates/user/upload_new_profile_picture.html.twig
<form action="" id='myForm' method="post" enctype="multipart/form-data">
    <label for="p_pic">
        {% if user.profile is null %}
            <img src="{{path('image_show',{path:'default',file: 'default.png'})}}"
            alt="profile picture| BookWorm" class="shadow-lg new_img"
            style="border: 4px solid rgb(165, 165, 163); height:100px; width:100px;margin-left: 100px;-moz-border-radius: 50px;-webkit-border-radius: 50px;border-radius: 50px;"
            itemprop="image">
        {% else %}
            <img src="{{path('image_show',{path:'profiles',file: user.profile})}}" alt="profile picture| BookWorm"
            class="shadow-lg new_img"
            style="border: 4px solid rgb(165, 165, 163); height:100px; width:100px;margin-left: 100px;-moz-border-radius: 50px;-webkit-border-radius: 50px;border-radius: 50px;"
            itemprop="image">
        {% endif %}
    </label>
    <input type="file" id="p_pic" name="profile_pic" accept=".jpg,.jpeg,.png,.webp" style="display: none;" mapped=false>
</form>